version: "3.3"
services:
  mailcatcher:
    restart: always
    image: dockage/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    expose:
      - "1025"

  strapi-db:
    image: postgres
    ports:
      - "5430:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: database
      POSTGRES_PASSWORD: database
    volumes:
      - /tmp/postgres/labfaz/strapi-db:/var/lib/postgresql/data

  api-db:
    image: postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: database
      POSTGRES_PASSWORD: database
    volumes:
      - /tmp/postgres/labfaz/api-db:/var/lib/postgresql/data
