version: "3.3"
services:
  strapi-db:
    image: postgres
    ports:
      - "5430:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: database
      POSTGRES_PASSWORD: database
    volumes:
      - /tmp/postgres/labfaz/strapi-db:/var/lib/postgresql/data

  api-db:
    image: postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: database
      POSTGRES_PASSWORD: database
    volumes:
      - /tmp/postgres/labfaz/api-db:/var/lib/postgresql/data
